name: Linux Clang Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libssl-dev zlib1g-dev

      - name: Build Debug
        run: CXX=clang++ make dev -j4

      - name: Build Release
        run: CXX=clang++ make rel -j4
