name: Windows MSYS2 MINGW Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-gcc make mingw-w64-x86_64-openssl mingw-w64-x86_64-zlib

      - name: Build Debug
        shell: msys2 {0}
        run: make STATIC_FLAG=-static dev -j4

      - name: Build Release
        shell: msys2 {0}
        run: make STATIC_FLAG=-static rel -j4
